// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerTableId } from "./tables/Player.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
